<?php $this->head = "Answers To Frequent Questions" ?>
<DIV style='margin-right:20px; margin-left:20px;'>
    <div id="mainContent"><img src="/media/photos/CVUUF_FAQs_photos.jpg" width="350" height="659" alt="" title="" align="right" />

          <a href="#am">Am I a UU?</a><br />
          <a href="#accessible">Is CVUUF's facility accessible?</a><br />
          <a href="#sunday">What are Sunday morning services like?</a><br />
          <a href="#services">What do people wear to services?</a><br />
          <a href="#visit">What will be expected of me at my first visit?</a><br />
          <a href="#child">What experience will my child have on a Sunday morning?</a><br />
          <a href="#chalice">Why do you light a chalice?</a><br />
          <a href="#origin">What is the origin of the name &quot;Unitarian Universalist&quot;?</a><br />
          <a href="#directions">What are the directions to the Conejo Valley UU Fellowship?</a><br />
          <a href="#believe">Can Unitarian Universalists believe anything they want?</a><br />
          <!--<a href="#famous">Who are some famous UUs?</a><br />-->
          <a href="#member">How does one become a member of CVUUF?</a><br /><br />


<br><br>
        <a name="am"></a>
        <h3>Am  I a UU?</h3>
        <p>Only  you can answer that question for sure. Many of our members have said, after  discovering UUism, &quot;I was a UU for years but just didn't know it yet!&quot; There  are several options that help you determine and decide if you identify with  UUism. You can meet with our Minister or one of our lay ministers to discuss  your beliefs, UUism, and how compatible they may be. Or visit a few of our  Sunday services and see how you relate to our message and values. We have  literature and information available as well. Some people have decided that  UUism might be right for them after taking the &quot;Belief-O-Matic&quot; 20-question  quiz on Beliefnet.com. We offer no official endorsement of the quiz, but if  you'd like give it a whirl, <a href="http://www.beliefnet.com/Entertainment/Quizzes/BeliefOMatic.aspx" target="_blank">click here</a>.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="believe"></a>
        <h3>Can  Unitarian Universalists believe anything they want?</h3>
        <p>No. It is true that ours is a free faith and that individual Unitarian Universalists have many varied beliefs about spirituality. At the same time, UUs  affirm a set of shared principles that form the foundation of our faith. One could not be considered a Unitarian Universalist and hold beliefs that are in  direct opposition or contradiction to the basic seven principles of Unitarian Universalism. <a href="principles">Click here</a> for these fundamental UU principles.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
          <a name="accessible"></a> 
          <h3>Is  CVUUF's facility accessible?</h3>
          <p>CVUUF  has two buildings; our Sanctuary, where worship services are held, and our  Fellowship Hall, which includes our kitchen and dining area, classrooms,  childcare space, library, and church offices. We also have a patio between the  two buildings where people socialize before and after our services. Each of our  buildings, the parking lots, our patio, and the restrooms, are accessible and  do not require the navigation of staircases. Our Fellowship Hall is two stories  tall and has an elevator.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="sunday"></a>
        <h3>What  are Sunday morning services like?</h3>
        <p>Our  Sunday services vary, but generally we start each service with a song, a reading, the lighting of our chalice, 
        and a  children's story. We collect food donations for the local 
        foodbank. The  children then leave for Religious Education classes. The sermon is usually  given by the 
        Rev. Lora Brandis, but we also have guest speakers, drama  groups, special music performances, and other 
        types of worship programs  depending on the topic. The service generally closes with extinguishing our chalice, a hymn, 
        and a benediction.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="services"></a>
        <h3>What  do people wear to services?</h3>
        <p>There  is no dress code. Some people wear jeans, others wear casual dress clothes, and  some prefer more formal attire. Please come in whatever clothes you feel most  comfortable wearing.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="visit"></a>
        <h3>What  will be expected of me at my first visit?</h3>
      <p>Our  greeters will reach out to shake your hand and welcome you with a smile. We  hope you'll respond by saying hello! We'll invite you to sign in on our visitor  register, and we'll make you a name tag. The visitor register and name tag are  optional; if you prefer to skip them that is fine. We hope you will stay after  the service for refreshments and conversation.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="child"></a>
        <h3>What  experience will my child have on a Sunday morning?</h3>
        <p>A  large room, called Childspace, for infants and toddlers is warm and inviting  with a professional child care staff. Child care is available at both services.</p>
        <p>For  preschool- through middle school-aged children, we have age appropriate  religious education classes at the first service and arts &amp; crafts for all  kids during the second service. The religious education classes focus on themes  relating to our Unitarian Universalist principles,  exposure to different beliefs and cultures and faith in action  projects. The atmosphere is one of that promotes acceptance of diverse ideas,  independent thinking, understanding of UU values and of world religions, and  celebrates the joy of learning. Children in these classes often form lifelong  friendships.</p>
        <p>For  high school youth, religious education takes place during the second service.  These classes are largely driven by themes and activities that are of interest  to youth themselves.</p>
        <p>Parents  can feel free to join their kids at our children's programs, or to keep their  children with them in the sanctuary during the worship service, if you wish.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="chalice"></a>
        <h3>Why  do you light a chalice?</h3>
         <p>Hans  Deutsch, an Austrian artist, first brought together the chalice and the flame  as a Unitarian symbol during his work with the Unitarian Service Committee  during World War II. To Deutsch, the image had connotations of sacrifice and  love. Unitarian Universalists today have many different interpretations of the  image. To many, the cup represents religious community, while the flame  represents ideas including the sacrificial flame, the flame of the spirit, and  more.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="origin"></a>
        <h3>What  is the origin of the name &quot;Unitarian Universalist&quot;?</h3>
        <p>Unitarian  Universalism emerged from two different religions: Unitarianism and  Universalism. 
        Both Unitarianism and Universalism started in Europe hundreds of  years ago. The Universalist 
        Church of America was founded by 1793, and the  American Unitarian Association by 1825. 
        In 1961, these denominations  consolidated to form the new religion of Unitarian Universalism. 
        For more  information, <a href="http://www.uua.org/publications/pamphlets/introductions/151249.shtml" target="_blank">click here</a>.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <a name="directions"></a>
        <h3>What  are the directions to the Conejo Valley UU Fellowship?</h3>
        <p>Our  address is 3327 Old Conejo Road, Newbury Park. CA.</p>
        <p>From  the South (Thousand Oaks): Take 101 Freeway to Newbury Park. Exit Wendy Drive south getting in  the middle lane. Turn left onto Wendy and cross over the freeway. Turn right  immediately at the signal onto Old Conejo Road.</p>
        <p>From  the North (Camarillo): Take 101 Freeway to Newbury Park. Exit Wendy Drive south and  continue straight onto Old Conejo Road.</p>
        <p>Proceed  to the signal at Ruth Dr and turn right into the office complex. Ours are the  last buildings on the left ahead toward the freeway. There is plenty of parking  all the way back.</p>
        <p><a href="http://www.mapquest.com/maps?city=Newbury+Park&amp;state=CA&amp;address=3327+Old+Conejo+Road#a/maps/l::3327+Old+Conejo+Rd:Newbury+Park:CA:91320-2115:US:34.190681:-118.945675:address:Ventura+Count" target="_blank">Click  here for a map.</a></p>
        <p class="backTop"><a href="#top">Back to top</a></p>
        <!--<a name="famous"></a>
        <h3>Who  are some famous UUs?</h3>
        <p>Lots  of people! To check some of them out, <a href="http://www.famousuus.com" target="_blank">click here</a>.</p>
        <p class="backTop"><a href="#top">Back to top</a></p>-->
        <a name="member"></a>
        <h3>How  does one become a member of CVUUF?</h3>
The Path to Membership is a Journey to a Deeper Commitment. We hope that your relationship with Conejo Valley Unitarian Universalist Fellowship 
will be spiritually, intellectually, and emotionally rewarding.         <p>If  you are ready to join our congregation, it's easy to become a member. Our path  to membership includes four steps:</p>
        <ul class="greenBulletList">
        	<li>To attend our &quot;Path to Membership&quot; class which provides an introduction  to the congregation and to the principles and history of Unitarian  Universalism.</li>
            <li>To sign our membership book and thereby declare yourself a part of the  community.</li>
            <li>To pledge a financial contribution to the church. The amount is your personal  decision. There are no minimums.</li>
            <li> To attend to your spiritual practice, through Sunday services, affinity or small groups, service on committee, and outreach opportunities.</li>
            
        </ul>
We are pleased you have chosen to worship with us, and we invite you to participate in our programs and activities, 
whether or not you are ready for full membership. When you are ready, membership will be a natural step, a way to 
express your joy in &mdash; and responsibility for &mdash; this faith community.
        <p class="backTop"><a href="#top">Back to top</a></p>
    </div>
</div>
</div>
