<?php $this->head = "Introduction to Our Congregation" ?>
<DIV style='margin-right:20px; margin-left:20px;'>
    <div id="mainContent">
    	<img src="/media/photos/CVUUF_Congregation_photos.jpg" width="350" height="457" alt="" title="" align="right" />
      
      <p>The  Conejo Valley UU Fellowship is located at 3327 Old Conejo Road in Newbury Park,  CA. CVUUF is a diverse and caring community of more than 200 members. We are a  welcoming congregation that affirms and promotes full participation in all our  activities and endeavors without regard to race, color, gender, physical or  mental challenge, affectional or sexual orientation, age, class or national  origin.</p>
      <p>We  believe that the spiritual quest is a personal one, based on individual  experiences, values, knowledge and sense of mystery. We also believe that by  coming together, we can deepen our spiritual understanding and work toward  realizing our statement of purpose:</p>
      
<blockquote>
      <p class="purpose" style="text-align:left;">The purpose of this Fellowship is to foster a liberal religious community, dedicated to the continuing search for truth bound by no dogma, restricted by no creed, and using 
      the democratic process. Affirming the essential dignity 
       and worth of every human being, we join in a fellowship in a quest of religious and ethical values to enrich our personal  lives, to grow in understanding of ourselves and of our world, and to serve others.  </p>
</blockquote>
    <p>CVUUF  was founded in 1961. Our interim minister is the Rev. Anne Hines, and we'll be searching for a settled minister to start in the Summer of 2016. The  congregation moved into our location on Old Conejo Road in Newbury Park in June  of 2008.</p>
    <strong><big>We  hope you will come and visit us! Sunday morning services are held at 9:15 and  11:00.</big></strong>
    <p><a href='https://maps.google.com/maps?q=Conejo+Valley+Unitarian+Universalist+Fellowship,+3327+Old+Conejo+Road,+Thousand+Oaks,+CA&hl=en&ll=34.191748,-118.945391&spn=0.011697,0.019419&sll=34.177015,-118.936958&sspn=0.093589,0.155354&oq=conejo&t=h&hq=Conejo+Valley+Unitarian+Universalist+Fellowship,&hnear=3327+Old+Conejo+Rd,+Newbury+Park,+Ventura,+California+91320&z=16&iwloc=A'>Click  here for a map to our building.</a></p>
    </div>
