<?php $this->head = "Our Principles" ?>
<DIV style='margin-right:20px; margin-left:20px;'>
    <div id="mainContent">
    	<img src="/media/photos/CVUUF_Principles_photos.jpg" width="350" height="442" alt="" title="" align="right" />

        <p>Our  faith draws on many religious traditions and welcomes people with different  beliefs. Rather than relying on creed or dogma, we are united by our shared  values. We join with Unitarian Universalist congregations across the country  and throughout the world in affirming and promoting these seven principles:</p>
        <ul class="greenBulletList">
          	<li>The inherent worth and dignity of every person;</li>
            <li>Justice, equity and compassion in human relations;</li>
            <li>Acceptance of one another and encouragement to spiritual growth in our  congregations;</li>
            <li>A free and responsible search for truth and meaning;</li>
            <li>The right of conscience and the use of the democratic process within our  congregations and in society at large;</li>
            <li>The goal of world community with peace, liberty, and justice for all;</li>
            <li>Respect for the interdependent web of all existence of which we are a part.</li>
        </ul>

        <div class="clearBoth">
        <h3>Beliefs  Within Our Faith</h3>
        <p>Unitarian  Universalism is a liberal religion that encompasses many faith traditions.  Unitarian Universalists include people who identify as Christians, Jews,  Buddhists, Hindus, Pagans, Atheists, Agnostics, Humanists, and others. As there  is no official Unitarian Universalist creed, Unitarian Universalists are free  to search for truth on many paths.</p>
        <p>To  quote the Rev. Marta Flanagan, &quot;We uphold the free search for truth. We  will not be bound by a statement of belief. We do not ask anyone to subscribe  to a creed. We say ours is a non-creedal religion. Ours is a free faith.&quot;</p>
        <p>Although we uphold shared principles, individual Unitarian Universalists have varied  beliefs about everything from scripture to rituals to God.</p></div>


        <div class="clearBoth">
        <h3>Sources of Our Living Tradition</h3>
        <p>Rev. Kathleen Rolenz said, “Throughout history, we have moved to the rhythms of mystery and wonder, prophecy, wisdom, teachings from ancient and modern sources, and nature herself.” Worshipping in our congregations you may hear a reading or perspective shared from any one of these sources from which our living tradition 
        is drawn:</div>
        </div>
        <ul class="greenBulletList">
          	<li>Direct experience of that transcending mystery and wonder, affirmed in all cultures, which moves us to a renewal of the spirit and an openness to the forces which create and uphold life;</li>
            <li>Words and deeds of prophetic women and men which challenge us to confront powers and structures of evil with justice, compassion, and the transforming power of love;</li>
            <li>Wisdom from the world's religions which inspires us in our ethical and spiritual life;</li>
            <li>Jewish and Christian teachings which call us to respond to God's love by loving our neighbors as ourselves;</li>
            <li>Humanist teachings which counsel us to heed the guidance of reason and the results of science, and warn us against idolatries of the mind and spirit;</li>
            <li>Spiritual teachings of earth-centered traditions which celebrate the sacred circle of life and instruct us to live in harmony with the rhythms of nature.</li>
        </ul>



    </div>
</div>
