<?php $this->head = "UU Voices" ?>
<DIV style='margin-right:20px; margin-left:20px;'>
<center>
    <div id="mainContent">
    	<div id="video">
    	<object width="700" height="500">
   	  <param name="movie" value="http://www.youtube.com/v/wezp1W2HKlU&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/wezp1W2HKlU&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="700" height="500"></embed></object></div>
	</div>
</center>
</div>
