<?php $this->head = "RELIGIOUS EDUCATION PARENTS" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
<form method=post>

<br><input TYPE='submit' name='Format' VALUE='PDF'> Generate PDF file to print
<br><br>

<table  border=2px style="empty-cells: show; background-color:white;" >
<tr><th>ID<th>Name<th>Status<th>Email<th>Phone<th>Address<th>Child ID<th>Child Name<th>Reg ID</tr>
    <?php $parents = $this->parents ?>
    <?php $last = -1 ?>
    <?php foreach ($parents as $parent) : ?>
<tr>
<?php if ($last == $parent[3]) : ?>
<td><td><td><td><td><td>
<?php else : ?>
<td><?php echo $parent[3] ?></td>
<?php $last = $parent[3] ?>
<td><?php echo $parent[4] . ' ' . $parent[5] ?></td>
<td><?php echo $parent[6] ?></td>
<td><?php echo $parent[7] ?></td>
<td><?php echo $parent[8] ?></td>
<td><?php echo $parent[9] ?></td>
<?php endif ?>
<td><?php echo $parent[0] ?></td>
<td><?php echo $parent[1] ?></td>
<td><?php echo $parent[2] ?></td>
</tr>
    <?php endforeach ?>
</table>