<span style='font-size:120%; font-weight:bold;'>Viewing the requested page requires authorization.</span>
<br><br>
<hr>
<span style='font-size:120%; font-weight:bold;'>If you have a password, fill in this section</span>
<br><br>    
<fieldset style="border:none; font-size:80%;">
    <?php echo $this->loginForm; ?>
</fieldset>
<br><hr>
<span style='font-size:120%; font-weight:bold;'>If you need a new password, fill in this section</span>
<br><br>
<fieldset style="border:none; font-size:80%;">
    <?php echo $this->newpassForm; ?>
</fieldset>
<br><hr>

<br><br>