<?php $this->head = "BULK EMAIL COMPOSITION" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<?php $this->tinyMCE = true ?>
<br><br>

<p>This feature is disabled by Jake (jakeholland.net@gmail.com) until we've got a process that reliably is compliant with CAN-SPAM. Please send me an email if you have a need to send bulk email, and I'll work with you to get it to happen. New instructions should be here within a few days of today (Nov 1, 2014), please let me know if they're not. :)

<p>The way we've been sending emails might cost us thousands of dollars if we continue. I apologize for the inconvenience, and I'm working to sort it out. If you're interested, please read up on the issues: <a href="http://www.business.ftc.gov/documents/bus61-can-spam-act-compliance-guide-business">FTC compliance guide</a>, <a href="http://www.spamhaus.org/consumer/definition/">Defacto standard definition of spam</a>.

<!--
<form method='post'>

<fieldset style="border:none;">
<dt>To:</dt>
<dd>
<input type="radio" style="border-style:none;" name="TO" value="ALL" > All in last two years
<input type="radio" style="border-style:none;" name="TO" value="CURRENT" checked> Current
<input type="radio" style="border-style:none;" name="TO" value="MEMBERS"> Members
<input type="radio" style="border-style:none;" name="TO" value="VISITORS"> Visitors
<input type="radio" style="border-style:none;" name="TO" value="RE"> RE
<input type="radio" style="border-style:none;" name="TO" value="TEST"> Test
</dd>
<dt>From:</dt>
<dd><input type="text" name="FROM" size="30" value="<?php echo $this->email ?>"></dd>
<dt>Subject:</dt>
<dd><input type="text" name="SUBJECT" size="40"></dd>
</fieldset>

<fieldset style="border:none;">
<dt>Your message:</dt>
<dd><TEXTAREA NAME="TEXT" COLS=70 ROWS=15></TEXTAREA></dd>
</fieldset>
<fieldset style="border:none;">
<dt> &nbsp; </dt>
<dd><small>Need help with entering data? <a href='http://www.freemasons-web.com/thirdParty/tiny_mce/themes/advanced/tinyMceHelp.html'>
tinyMCE help</a></small></dd>
<br><br>

<dt><INPUT TYPE=SUBMIT name='doit' VALUE="SUBMIT"></dt>
<dd>Expect a minute or two so silent delay after <b>Submit</b> while emails are sent.</dd>
</fieldset>

</FORM>
-->

