<?php $this->head = "BULK EMAIL COMPOSITION" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<?php $this->tinyMCE = true ?>
<br><br>

<p>The way we're doing bulk email now is through mailchimp. They provide a service which is compliant with all the spam laws, and through which we maintain a list of all the people who have consented to receive bulk emails from us, including nearly all of our members.</p>
<p>If you just need to send one email, please contact me (<a href="mailto:jakeholland.net@gmail.com">jakeholland.net@gmail.com</a> or 805-501-5345) and I'll work with you to get it sent to the appropriate group. If you need to send emails regularly, I'll get you set up with permissions on mailchimp so you can do that.</p>
<p>The way we were doing emails before was getting us on spam blacklists, which meant that no emails were going through at all. This has continued to be a problem sometimes, but is happening less frequently now. My current plan is to transition the rest of the emails to another system, probably google groups, hopefully in a way that is mostly transparent and does not require hundreds of people to make manual changes to the way they handle communications today. That's in (slow) progress. I apologize for the inconvenience.</p>

<!--
<form method='post'>

<fieldset style="border:none;">
<dt>To:</dt>
<dd>
<input type="radio" style="border-style:none;" name="TO" value="ALL" > All in last two years
<input type="radio" style="border-style:none;" name="TO" value="CURRENT" checked> Current
<input type="radio" style="border-style:none;" name="TO" value="MEMBERS"> Members
<input type="radio" style="border-style:none;" name="TO" value="VISITORS"> Visitors
<input type="radio" style="border-style:none;" name="TO" value="RE"> RE
<input type="radio" style="border-style:none;" name="TO" value="TEST"> Test
</dd>
<dt>From:</dt>
<dd><input type="text" name="FROM" size="30" value="<?php echo $this->email ?>"></dd>
<dt>Subject:</dt>
<dd><input type="text" name="SUBJECT" size="40"></dd>
</fieldset>

<fieldset style="border:none;">
<dt>Your message:</dt>
<dd><TEXTAREA NAME="TEXT" COLS=70 ROWS=15></TEXTAREA></dd>
</fieldset>
<fieldset style="border:none;">
<dt> &nbsp; </dt>
<dd><small>Need help with entering data? <a href='http://www.freemasons-web.com/thirdParty/tiny_mce/themes/advanced/tinyMceHelp.html'>
tinyMCE help</a></small></dd>
<br><br>

<dt><INPUT TYPE=SUBMIT name='doit' VALUE="SUBMIT"></dt>
<dd>Expect a minute or two so silent delay after <b>Submit</b> while emails are sent.</dd>
</fieldset>

</FORM>
-->

