<?php $this->head = "SEXTONS" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
<center>
<strong><big>This directory information is for exclusive use by CVUUF Members and Friends
and is not to be used for any commercial purposes.</big></strong>
</center>
<br><br>

<br><br>
<strong><big>SEXTONS SCHEDULE</big></strong>
<fieldset style="border:none; ">
<br><br>
    <form method=post>
<fieldset style="border:none; ">

<table  border=2px style="empty-cells: show; background-color:white;" >    
<tr><th><th><?php echo $this->initialsBoxes ?></tr>
<tr><th><th>Date<?php echo $this->initialsList ?></tr>
  <?php foreach($this->table as $date) : ?>
<tr>
<td><input type="checkbox" name="did[]" value='<?php echo $date[0] ?>' >
<td><?php echo $date[1] ?>
    <?php foreach ($date[2] as $column) : ?>
<td class="centered-cell"><?php echo $column ?>
    <?php endforeach ?>  
</tr>
  <?php endforeach ?>  
</table>
<input TYPE=hidden name='todo' VALUE='status'>
<br>
<dt><input TYPE=SUBMIT name='status' VALUE='AWAY'></dt><dd>Set status to 'away' x|x for one person on date(s)</dd>
<dt><input TYPE=SUBMIT name='early' VALUE='EARLY SCHEDULED'></dt><dd>Set status to 'early' S|  for one person on date(s)</dd>
<dt><input TYPE=SUBMIT name='late' VALUE='LATE SCHEDULED'></dt><dd>Set status to 'late'  |S for one person on date(s)</dd>
<dt><input TYPE=SUBMIT name='status' VALUE='SCHEDULED'></dt><dd>Set status to 'both' S|S for one person on date(s)</dd>
<dt><input TYPE=SUBMIT name='status' VALUE='CLEAR'></dt><dd>Clear status for one person on date(s)</dd>


</fieldset>

<hr>
<br><br>
<strong><big>SEXTONS PEOPLE</big></strong>
<br><br>

<table  border=2px style="empty-cells: show; background-color:white;" >    
<tr><th><th>Name<th>Initials</tr>
  <?php foreach($this->people as $person) : ?>
<tr>
<td><input type="checkbox" name="pid[]" value='<?php echo $person[0] ?>' >
<td><?php echo $person[1] ?>
<td><?php echo $person[2] ?>
</tr>
  <?php endforeach ?>
</table>

<br><input type="submit" name="addbutton" value="ADD"> Add new initials for ID#
<input type="text" name="id" value="" size="4"> or Name 
<input type="text" name="name" value="" size="40">
<br><br><input TYPE="submit" name='removebutton' VALUE='REMOVE'> Remove selected people - BE CAREFUL!!<br>
    </form>