<?php $this->head = "INTRODUCING THE CVUUF LIBRARY" ?>

<p>
<center><img src='images/library002.jpg' height=400px width=533px border='4px, solid' alt='Library Photo'><br>
The library collection in the Board room.</center>
<p>
Want to learn more about Unitarian Universalism? Or maybe you need some readings for a worship service or a social gathering?  
Or books on parenting with a UU approach?  Come to our library.  We have a great collection to aid you on your spiritual 
journey including self-help books, psychology, major religions including goddess religion and paganism.  Our collection 
numbers over 1500 items and is fully accessible by an online catalog by keyword, author, title, and subject. 
<p>
The majority of our books are in the Board Room on the second floor of Fellowship Hall. There are others at point of usage: 
The Children&#8217;s Activity Room, Young Religious UU Room, Adult Religious Education Room, and Social Hall. 
<p>
<b><u>Borrowing Materials</u></b><br>
Library materials may be borrowed by anyone in the Fellowship Directory. Loans on most items are for one month.
<p>
For more information and for reader&#8217;s advice, contact our librarian by email to library@cvuuf.org