<?php $this->head = "Rev. Lora Brandis" ?>

<div style='width:245px; height:364px; float:left;'>
<br>
<img style='border:6px groove black;'
src="/media/photos/Rev_Lora.jpg" align=left 
alt="Rev. Lora.jpg">
<div style='font-size:60%; text-align:center; '>Photo by Jon Delorey</div>
</div>

<p>Welcome to the Conejo Valley Unitarian Universalist
Fellowship. </p>
<p class=MsoNormal>I began serving this congregation in August of 2011.
Although my call to the ministry came when I was quite young, I didn’t enter
seminary until later in life after I had become a Unitarian Universalist. I
started attending the First Unitarian Church of Dallas when our children were
young, wanting them to have a religious education that taught them there were
many paths to the holy. Like many adults who first come to one of our churches
for their children, I ended up staying for my own spiritual journey. I was a
bit surprised by where my journey led.</p>

<p class=MsoNormal>I have a background in theatre and non-profit management. My
impetus to have a career in theatre came from my desire, like that of any other
artist, to hold up a mirror for people to see themselves more deeply, thereby
gaining awareness and insight. The power of any art form is its potential to
transform the human spirit. I was drawn to theatre for much the same reason I
am drawn to the ministry.</p>

<p class=MsoNormal>I have a BFA in Theatre and a BA in Ibero-American Studies,
with a minor in Spanish from Southern Methodist University. Twenty-three years
after I completed my undergraduate degrees I returned to SMU to attend Perkins
School of Theology. I served my internship at Horizon Unitarian Universalist
Church in Carrollton, Texas and my first year in ministry was spent as a
consultant for two churches 150 miles apart in Salt Lake City, UT and
Pocatello, ID. I have many stories to tell from that adventure.</p>

<p class=MsoNormal>Why am I a Unitarian Universalist? The answer to this
question changes as my faith matures and my journey takes me to new places. Here’s
how I answer that question for now, “I am a Unitarian Universalist because I am
a pilgrim and Unitarian Universalists are a pilgrim people.” Come and join us
on the journey!</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><i>Rev. Lora
keeps office hours on Tuesday, Wednesday and Friday by appointment. She is off
on Mondays. To reach her, please email her at </i><a
href="mailto:minister@cvuuf.org"><i>minister@cvuuf.org</i></a><i>. You may
follow her blog here: </i><a href="http://lorabrandis.wordpress.com/"><i>http://lorabrandis.wordpress.com/</i></a><i>.</i></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><i>&nbsp;</i></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><i>&nbsp;</i></p>
