<?php $this->head = "Sunday Services at 9:15 and 11 AM" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
  
    <?php foreach ($sundays as $sunday : ?>
<center>
  <?php echo date('F', mktime(0, 0, 0, substr($sunday->sunday, 5, 2), 1, 2013)) ?>


    <?php endforeach ?>