<?php $this->head = "Adult Religious Education" ?>
<br><br>

<p>Religious education is available for adults on an on-going basis. Each year we choose a theological theme, exploring it together as a congregation through worship, story and in the classroom. Classes are taught by professional staff as well as lay leaders. Classes are usually held one night a week and can last between 4-13 weeks.
<p>For the 2013-2014 year we will explore the Twelve Steps to a Compassionate Life based on the book of the same name by Karen Armstrong.   Groups for discussion on the topic will be formed and facilitated by Rev. Lora Brandis or Justine Fischer, Director of Religious Education. For more information contact Justine at dre@cvuuf.org.  Dates and times will be listed in on cvuuf.org/calendar or in the newsletter.
<p><br><b>Adult Religious Education Classes:</b><br>
<b>Compassion Conversations</b> - Third Sunday of every month from 12:15 to 1:30.  An opportunity to journal and discuss the monthly compassion theme.  The discussion is facilitated alternately by Rev. Lora and Justine, DRE. For more information contact Justine at dre@cvuuf.org.  