<?php $this->head = "SMALL GROUP CHARTER" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br>
<?php $charter = $this->charter;
      $label = $this->label;
//var_dump($charter); exit;
?>
<form method='post'>


<p>
<fieldset style="border:none;">
<dt><?php echo $label['name']?></dt>
<dd>
<input type="text" name="name" value='<?PHP echo $charter->groupname ?>' size="50"  <?php echo $this->disabled?>>
</dd>
</fieldset>

<?php 
  $disabled = $this->disabled;
  $readonly = $this->readonly;
  $label = $this->label;

  $GroupTypeStr = $this->type;
	$gtypes_s['Activity'] = $gtypes_s['Service'] = $gtypes_s['Support'] = $gtypes_s['Social'] = '';
  $gtypes = explode(",", $GroupTypeStr);
	foreach ($gtypes as $gtype)
		$gtypes_s[$gtype]='checked';
?>

<fieldset style="border:none;">
<dt><?php echo $label['type']?></dt>
<dd>
<input type='checkbox' name='type[]' value='Activity' <?php echo $disabled ?>,
   <?php echo $gtypes_s['Activity'] ?>><span>Activity Group</span>
<input type='checkbox' name='type[]' value='Service' <?php echo $disabled ?>,
   <?php echo $gtypes_s['Service'] ?>><span>Service Group</span>
<input type='checkbox' name='type[]' value='Support' <?php echo $disabled ?>,
   <?php echo $gtypes_s['Support'] ?>><span>Support Group</span>
<input type='checkbox' name='type[]' value='Social' <?php echo $disabled ?>,
   <?php echo $gtypes_s['Social'] ?>><span>Social Group</span>
</dd>
</fieldset>

<fieldset style="border:none;">
<dt><?php echo $label['nmem']?></dt>
<dd>
<input type="text" name="nmem" value='<?PHP echo $this->charter->numbermembers ?>'size="10" <?php echo $readonly?>>
</fieldset>

<fieldset style="border:none;">
<dt><?php echo $label['purp']?></dt>
<dd>
<textarea name="purp" cols=50 rows=5 <?php echo $readonly?>  <?php echo $this->textstyle?>>
<?PHP echo $this->charter->purpose?>
</textarea>
</dd>
</fieldset>


<?php 
	$gtypes_s[0] = $gtypes_s[1] = $gtypes_s[2] = $gtypes_s[3] = '';
  $inc = $this->charter->inclusivepolicy;
//var_dump($inc);
  if ($inc <> '')
  {
    if ($inc[0] == 'O')
        $idx = 0;
    elseif ($inc[12] == 's')
        $idx = 2;
    elseif ($inc[32] == 'f')
        $idx = 1;
    else
        $idx = 3;
    $gtypes_s[$idx] = 'checked';
  }

?>

<fieldset style="border:none;">
<dt><?php echo $label['incl']?></dt>
<dd>
<input type='checkbox' name='incl[]' value='Open and publicized' <?php echo $disabled ?>,
   <?php echo $gtypes_s[0] ?>><span>Open and publicized</span>
<br><input type='checkbox' name='incl[]' value='Closed with publicized openings for new members' <?php echo $disabled ?>,
   <?php echo $gtypes_s[1] ?>><span>Closed with publicized openings for new members</span>
<br><input type='checkbox' name='incl[]' value='Closed with seeding of new groups when necessary' <?php echo $disabled ?>,
   <?php echo $gtypes_s[2] ?>><span>Closed with seeding of new groups when necessary</span>
<br><input type='checkbox' name='incl[]' value='Closed with publicized openings and seeding' <?php echo $disabled ?>,
   <?php echo $gtypes_s[3] ?>><span>Closed with publicized openings and seeding</span>
</dd>
</fieldset>

<fieldset style="border:none;">
<dt><?php echo $label['conf']?></dt>
<dd>
<textarea name="conf" cols=50 rows=5 <?php echo $readonly?>  <?php echo $this->textstyle?>>
<?PHP echo $this->charter->confidentialitypolicy?>
</textarea>
</dd>
</fieldset>

<fieldset style="border:none;">
<dt><?php echo $label['mloc']?></dt>
<dd>
<input type="text" name="mloc" value='<?PHP echo $this->charter->meetinglocation ?>' size="60" <?php echo $readonly?>>
</fieldset>

<fieldset style="border:none;">
<dt><?php echo $label['meet']?></dt>
<dd>
<input type="text" name="meet" value='<?PHP echo $this->charter->meetings ?>' size="60" <?php echo $readonly?>>
</fieldset>

<fieldset style="border:none;">
<dt><?php echo $label['nonc']?></dt>
<dd>
<textarea name="nonc" cols=50 rows=5 <?php echo $readonly?>  <?php echo $this->textstyle?>>
<?PHP echo $this->charter->noncvuufpolicy?>
</textarea>
</dd>
</fieldset>

<fieldset style="border:none;">
<dt><?php echo $label['appr']?></dt>
<dd>
<input type="text" name="appr" value='<?PHP echo $this->charter->approvaldate ?>' size="10" <?php echo $readonly?>>
</dd>
</fieldset>


  <input TYPE=HIDDEN name='recid' value="<?php echo $this->recid?>">
  <input TYPE=HIDDEN name='lock' value="<?php echo $this->lock?>">
  <input TYPE=HIDDEN name='newold' value="<?php echo $this->newold?>">
<br><br>
<fieldset style="border:none;">
  <?php if ($this->newold == 'new') : ?>
<dt>&nbsp;</dt>
<dd>
<input class='submit' TYPE=SUBMIT name='todo' value='NEW'> Create new charter.
</dd>
  <?php else : ?>
    <?php if ($this->readonly == '') : ?>
<dt>&nbsp;</dt>
<dd>
<input class='submit' TYPE=SUBMIT name='todo' value='FILE'> File this charter.
</dd>
    <?php else : ?>
<dt>&nbsp;</dt>
<dd>
<input class='submit' TYPE=SUBMIT name='todo' value='UNLOCK'> Unlock charter for editing.
</dd>
    <?php endif ?>
  <?php endif ?>

<br><br>    
<dt>&nbsp;</dt>
<dd>
<input class='submit' TYPE=SUBMIT name='todo' value='DIR'> Go to charter directory.
</dd>
</fieldset>

</form>
<br><br>