<?php $this->head = "INFO ACTION TEST" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br>
<?php $this->tinyMCE = true ?>
<form method='post'>
<textarea name="purp" cols=50 rows=10 >
Here is some editable text.
</textarea>
