<?php $this->head = "Calendar Rooms Admin" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>


<FORM ID="CalRoomsAdmin" METHOD=POST>


<br><br>

<form method=post>

<table  border=2px style="empty-cells: show; background-color:#F4F3EE;" >
<tr><th>ID<th>X<th>Room Name<th>Room Code<th>Non-User Cal</tr>
    <?php $table = $this->data ?>
    <?php foreach($table as $row) : ?>

<tr>
<td><?php echo $row[0] ?><td>
<input type="checkbox" name="id[]" value='<?php echo $row[0] ?>' >
<td><?php echo $row[1] ?><td> <?php echo $row[2] ?>
<td> <?php echo $row[3] ?></tr>

    <?php endforeach ?>
</table>

<br><input TYPE=SUBMIT name='roomAction' VALUE='NAME'> Change room name to  
			<INPUT type='text' name='newRoomName' size=25>
<br><input TYPE=SUBMIT name='roomAction' VALUE='CODE'> Change room code to  
			<INPUT type='text' name='newRoomCode' size=2>
<br><br><input TYPE=SUBMIT name='roomAction' VALUE='ADD'> ADD Room named
			<INPUT type='text' name='newRoom' size=25><br><br>
<input TYPE=SUBMIT name='roomAction' VALUE='DROP'> Remove selected Room - BE CAREFUL!!<br>

</FORM><br>