<?php $this->head = "Permissions Administration" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>

<br><br>
<span style='font-size:120%; font-weight:bold;'><?php echo "Users with additional permissions" ?></span><br><br><br>
<fieldset style="border:none; ">
    <?php echo $this->permForm; ?>
</fieldset>

    <?php $specials = $this->special ?>
    <form method=post>
<table  border=2px style="empty-cells: show; background-color:#F4F3EE;" >
<tr><th>X<th>ID<th>Name<th>Level</tr>
    <?php foreach ($specials as $user) : ?>
<tr>
<td><input type="checkbox" name="id[]" value='<?php echo $user[0] ?>' >
<td><?php echo $user[0] ?>
<td><?php echo $user[1], ' ', $user[2] ?> 
<td><?php echo $user[3] ?>
</tr>
    <?php endforeach ?>
</table>

<br>
<input type="hidden" name="perm" value="<?php echo $this->perm ?>">
<input type="submit" name="modifybutton" value="MODIFY">
Modify first 'X' record permissions
    </form>