<?php $this->head = "Permissions Administration" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>

<br><br>
<span style='font-size:120%; font-weight:bold;'><?php echo "Permissions for one person" ?></span><br><br><br>
<fieldset style="border:none; ">
    <?php echo $this->personForm; ?>
</fieldset>


    <?php if (isset($this->names)) : ?>
<br><hr><br>
    <form method=post>
<table  border=2px style="empty-cells: show; background-color:#F4F3EE;" >
<tr><th>X<th>ID<th>Name<th>Status</tr>
    <?php foreach ($this->names as $name) : ?>
<tr>
<td><input type="checkbox" name="id[]" value='<?php echo $name[0] ?>' >
<td><?php echo $name[0] ?>
<td><?php echo $name[1] ?> 
<td><?php echo $name[2] ?> 
</tr>
    <?php endforeach ?>
</table>
<br>
<input type="hidden" name="perm" value="<?php echo $this->perm ?>">
<input type="submit" name="personbutton" value="PERSON">
Select first 'X' person
    </form>    
    <?php endif ?>