<?php $this->head = "Permissions Administration" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
<hr><br>
    <?php endif ?>

<br><br>
<span style='font-size:120%; font-weight:bold;'><?php echo "Change permissions for $this->name" ?></span><br><br><br>
<fieldset style="border:none; ">
    <?php echo $this->permForm; ?>
</fieldset>
