<?php $this->head = "COMMUNITY OUTREACH" ?>

<center>

<br><br><strong>Transformation occurs when we act and educate.</strong>
</center>
<br><br>
Our Social Actions are primarily focused to help those marginalized by poverty, immigration, homeless and those in need within our community in the Conejo Valley and surrounding areas. In addition, we act to support peace, liberty and justice for all. 
<br><br>
<span style="font-size:120%; font-weight:bold;">OUR CURRENT PROGRAMS</span>
<br><br>
<u><strong>Community Forum:</strong></u> An ongoing series of speakers, films and socially relevant entertainment events.  Our aim is to organize and present public programs that inform, inspire and delight our community.   We present monthly (or more) events that focus on justice issues…. From economic, environmental, reproductive, immigration, etc.   We bring in speakers, show documentaries (often followed by lively conversations), present plays, concerts, etc.  Community Forum will present our 100th event in August of 2013.  We invite your participation by joining us on our planning committee, ushering at events or simply joining us. 
<br><br>
<u><strong>Feeding Hands:</strong></u>  First Tuesday of the month we prepare, cook and serve meals to feed 50-100 people in need at the Calvary Community Church, Westlake Village.  A wonderful way to put your faith into action--  Your participation can be done on an occasional basis, or monthly.  We have home cooks who drop off side dishes at CVUU or at Calvary.  Others who help prepare a main dish in the CVUUF kitchen.  Some serve Tuesday evening or do a brief cleanup in our kitchen the next day, Wednesday. Reimbursement is available for food you purchase.  
<br><br>
<u>
<strong>MICOP:</strong></u> Join in the fun with the children of our Mixteco farm workers. Each month MICOP (Mixteco Indigena Community Organizing Project) holds a meeting to share information, provide food and other services to our local farm workers. While the parents are meeting we share a craft with the children.  MICOP meetings are held in Oxnard and El Rio.  3-6 pm. This is a great opportunity for child and youth participation.   
<br><br>
<u> 
<strong>Westminster Free Clinic Holiday Family Adoption:</strong></u>  We adopt families from the Clinic. Many of these families are working multiple jobs but can't make ends meet due to health constraints, injuries or medical care costs.  We generously donate household supplies, gift cards for markets or stores, clothing and gifts from a child's wish list.
<br><br>
<u><strong>Manna</strong></u>:  Each Sunday Service we collect canned food and other items for Manna Conejo Valley Food Bank. Items needed are listed in News&Notes, the monthly Newsletter and the online Announcements.
<br><br>
<u>
<strong>Special Collections:</strong></u>  Sunday, once a month the plate collections go to assist local organizations servicing those in need. 
<br><br>
<u><strong>Coffee and chocolate sales:</strong></u>  Each Sunday. The Unitarian Universalist Service Committee Coffee Project is a collaboration between UUSC and Equal Exchange, a worker-owned, fair trade company based in West Bridgewater, Mass. Equal Exchange sources these goods directly from farmer cooperatives, following the standards and principles of fair trade on 100% of its products. The profits belong to our Fellowship. 
<br><br>
<br><br>

<span style="font-size:120%; font-weight:bold;">Other programs - Past and Ongoing Social Justice Work:</span>
<br><br>
<u><strong>Affiliation with MoveToAmend:</strong></u>  Support for a Constitutional Amendment to firmly establish that money is not speech, and that human beings, not corporations, are persons entitled to constitutional rights.
<br><br>
<u><strong>Justice for Immigrants</strong></u>
<ul>
<li>There is strong support for just, humane and comprehensive immigration reform.   Many members understand immigration as a moral issue and Stand on the Side of Love with immigrants seeking a path to citizenship.
<li>In addition, people participate with the <a href="http://uujmca.org/our-work/immigrantjustice/">UU Justice Ministry of California</a> in support of the Trust Act (AB 4) to save local resources and help rebuild confidence between immigrant communities and local police. 
<li> Many believe it is not right for families to be broken apart by deportation or detention because of immigration status.  A number of members have volunteered to visit immigrants held in a remote, for-profit detention center to help end their isolation.  
</ul>

<u><strong>We support Gender Rights:</strong></u>
<ul>
<li>We Stand on the Side of Love by supporting Same Sex Marriage
<li>We support marriage equality, and oppose Defense Of Marriage Act (DOMA)
</ul>

<ul>
Letter writing to prisoners in solitary confinement:</u>
<li>Solitary confinement is torture. Keeping a person alone in a small, windowless room for 23 hours a day is torture. Humans are social beings who need interaction with other human beings.
<li>We write cards and letters to men in solitary confinement so they know they are not forgotten. This, we believe, reaffirms their, as well as our humanity. 
</ul>
<br><br>
For more information on any of our programs please contact our Outreach Director at <a href='mailto:outreachdirector@cvuuf.org?Subject=Asking%20for%20information' target="_top">Outreachdirector@cvuuf.org</a> 
<br><br>
