<div class="heading" align="center" style="font-size: 18pt">
Welcome!</div>

<p>Unitarian Universalist minister Norman Naylor once wrote these words that are some of my favorites with which to begin Sunday worship:</p>

<blockquote>Do not leave your cares at the door. Do not leave there your pain, your sorrow or your joys. Bring them with you into this place of acceptance and forgiveness. Place them on the common altar of life. Come then, and offer yourself to potential transformation by the creative process that flows through you and all life.</blockquote>

<p>I love these words because they speak of an insistence that each of us is enough as we are; that everyone is welcome here with sorrows, pain, joys, with all our strengths and all our ragged edges. We invite you to bring your whole self to this Fellowship, and join us in community as we worship, laugh, cry, sing as we wrestle with the deep issues of life, help our children explore their beliefs, and work to create a world of justice and peace.</p>

<p>There are numerous spiritual practices that can be accomplished alone -- meditation, walking on the beach, listening to beautiful music, etc.; perhaps you have such a practice, and that is good. But it is in community that our spiritual practice can take root can come alive in covenantal relationship, in something greater than ourselves. It is in community that the potential for transformation lies.</p>

<p>So I invite you to join us just as you are, and wherever you are on your spiritual path as we open ourselves to the possibilities of spiritual transformation, for ourselves and for our world.</p>

Blessings...<br/>
Reverend Anne
