<div class="heading" align="center" style="font-size: 18pt">
      Welcome!</div>
      
<p >We often sing,
“Come, come, whoever you are, wanderer, worshiper, lover of leaving. Ours is no
caravan of despair. Come, yet again come.” As Unitarian Universalists we sing
these words as an offering of radical hospitality. We sing these words because
we know what it is to wander among beliefs, building our own theologies from
remnants of personal experience and the wisdom of the ages. We sing these words
because many of us have left churches, temples and religions that no longer
make sense to us. And we sing these words lighting the candle of hope against
the darkness of despair.

<p >We sing these
words together as the covenanted community committed to nurturing spiritually
courageous people who transform the world through justice and compassion. This
is not a small thing; this is not an insignificant commitment.


<p >“Come, come,
whoever you are” is the invitation from the church of the radical welcome. You
have just said yes to this invitation. You answered yes to the invitation to
stand in a shared vulnerability, meeting in the space where the “I” begins to
dissolve and the “we” begins to take shape.

<p >Take your time
standing in that sacred space where the “I” begins to dissolve and the “we”
begins to take shape. Take your time deciding how you will serve this
community. Listen for what calls you. Listen as the community sings to you,
“Come, come, whoever you are!”

<p >Listen and
come to worship on Sunday mornings. Listen and join a Chalice Circle group, a
special interest group, or a Faith In Action activity. Listen and attend our
Community Forum. Listen to your new community as they sing a song of welcome.

<p>In faith,</p>

<p >Rev. Lora</p>

</div>

</body>

</html>
