<?php $this->head = "CALENDAR EVENT SUBMISSION" ?>
<p>
The new process for getting an event scheduled on the calendar is:
<!-- <a href="http://members.cvuuf.org/calendar">CVUUF calendar</a> -->
<ol>
<li>Check the <a href="https://cvuuf.org/blog/rooms-calendar/">CVUUF calendar</a>
to be sure the date, time, and room are available</li>
<li>fill out the <a href="https://cvuuf.org/blog/room-reservations/">Room Request Form</a>.<br/>
Be sure to include your correct email address, in case there are any questions before approval.</li>
<li>If this is a public event, ALSO please fill out the <a href="https://cvuuf.org/blog/request-new-event/">New Public Event Form</a>.</li>
</ol>
<br/>
If you have trouble with that, you can instead send an email with your request to:<br/>
<ul>
<li><a href="mailto:calendar@cvuuf.org?body=Hello%20Calendar%20team%2C%0AI%20would%20like%20to%20put%20an%20event%20on%20the%20calendar.%0A%0ATitle%3A%0ADescription%3A%0ARoom%28s%29%20to%20reserve%3A%0ADate%20and%20time%3A%0ARepeating%3F%20%28How%20often%20and%20when%3F%29%3A%0AContact%3A%0A%0AThanks%2C%0A&subject=Calendar%20Request">calendar@cvuuf.org</a></li>
</ul>
Then Andy Pletcher (or another member of the calendar team, if she is unavailable) will put it on the calendar and let you know, or reply to ask followup questions, if more information is needed.
</p>
<p>
Each email should include:<br/><br/>
Event Name<br/>
Rooms Requested (or a location)<br/>
Date<br/>
Time (Beginning &amp; End)<br/>
Contact Name<br/>
Description to put on the website<br/>
Image or photo (optional but preferred)<br/>
</p>
<p>
If you have any questions, please email <a href="mailto:council@cvuuf.org?body=Dear%20Council%2C%0AI%20have%20a%20question%20about%20an%20event%20I%27d%20like%20to%20have%20at%20the%20church%3A%0A&subject=Calendar%20Event%20Question">council@cvuuf.org</a> to talk it over. Especially if you are concerned your event might not be seen by everyone as serving our mission to nurture spiritually courageous people who transform the world through justice and compassion
</p>

