<?php $this->head = "CALENDAR EVENT SUBMISSION" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>


<FORM ID="CalendarRequest" METHOD=POST>


<br><br>
<dt>Your first name:</dt>
<dd>
<input type="text" readonly name="first_name" value="<?PHP echo $this->firstname; ?>" size="30">
</dd>
<br><dt>Your last name:</dt>
<dd>
<input type="text" readonly name="last_name" value="<?PHP echo $this->lastname ?>" size="30">
</dd>
<br><dt>Your email address:</dt>
<dd>
<input type="text" readonly name="email" value=<?PHP echo $this->email ?> size="40">
</dd>
<br><strong><big>
<blockquote style="background: transparent;">If this is not you, please inform our <a href='/index/contact'>webcrafter</a>.
</big></strong>
</blockquote>
<br>
<dd>
<input type=hidden id='submitid' name='submitid' value='<?php echo $this->id ?>'>
</dd>
<br><hr><br>

<div class="heading">Approvals</div>
<blockquote style="background: transparent;">All event requests are posted as pending approval 
and display as <span style="color:#97575B; font-style:italic;">dull red italic text</span> 
on the calendar until the event is 
approved by a Council Group Director and, if the CVUUF
facility is used, by the Scheduling Coordinator.  This is true for both new and changed events, with
the exception that changes in the event description only do not require approval.<p/>
If you're stuck on something on this page or with the scheduling in general, contact Andy Pletcher (<a href="mailto:andypletcher@gmail.com">andypletcher@gmail.com</a>) and she'll be happy to help walk you through the process.
</blockquote>

<dt>Council Group</dt>
<dd>
<select name="eventgrp">
<?php $names = $this->groupnames ?>
<?php foreach ($names as $name) : ?>
  <option value='<?php echo $name ?>'><?php echo $name ?></option>
<?php endforeach ?>
  <option selected value="None">Choose</option>
</select></dd>

<br><br><hr><br>

<dt>Is this new or a change?</dt>
<dd>
  <select name="ischange">
    <option value="change">change</option>
    <option selected value="new">new</option>
  </select>
</dd>

<br><br>
<fieldset style="border:none; ">
<div class="heading">Change Event</div>
<br>
<dt>Event ID to change</dt>
<dd>  
  <input type="text" name="eventold" size="4">
</dd>

<dt>Describe the change</dt>
<dd>
  <textarea name="changedesc" cols=50 rows=5></textarea>
</dd>
<br><br><br><br>
<dt>Submit your change request</dt>
<dd>
  <INPUT class='submit' TYPE=SUBMIT VALUE="SUBMIT" ID='submitbutton'>
</dd>
</fieldset>

<br><br><br><br>

<fieldset style="border:none; ">
<div class="heading">New Event</div>

<br>

<dt>Title</dt>
<dd>
  <input type="text" name="eventname" size="50">
</dd>

<dt>Date</dt>
<dd>

<input id='start_dt' name="eventdate" value='DD-Mon-YYYY' class='datepicker'><small>Click image for calendar</small>


</dd>

<dt>Starting Time</dt>
<dd>

  <select name="eventtimehour">
  <?php
  echo "\n<option value=\"" . 0 . '">' . '12a' . '</option>';	
  for($i=1;$i<12;++$i) {
    echo "\n<option value=\"" . $i . '">' . $i .'a' . '</option>';
  }
  echo "\n<option selected value=\"" . 12 . '">' . '12p' . '</option> ';	
  for($i=1;$i<12;++$i) {
    echo "\n<option value=\"" . ($i+12) . '">' . $i.'p' . '</option>';
  }
  ?>
  </select>
</dd>
<dd>
  <select name="eventtimeminute">
  <?php
  for($i=0;$i<10;$i+=5) {
    echo '<option value="' . $i . '">' . '0' . $i . '</option>';
  }	
  for($i=10;$i<60;$i+=5) {
    echo '<option value="' . $i . '">' . $i . '</option>';
  }
  ?>
  </select>    
</dd>

<dt>Ending Time</dt>
<dd>
  <select name="eventendhour">
  <?php
  echo "\n<option value=\"" . 0 . '">' . '12a' . '</option>';	
  for($i=1;$i<12;++$i) {
    echo "\n<option value=\"" . $i . '">' . $i .'a' . '</option>';
  }
  echo "\n<option selected value=\"" . 12 . '">' . '12p' . '</option> ';	
  for($i=1;$i<12;++$i) {
    echo "\n<option value=\"" . ($i+12) . '">' . $i.'p' . '</option>';
  }
  ?>
  </select>
</dd>
<dd>
  <select name="eventendminute">
  <?php
  for($i=0;$i<10;$i+=5) {
    echo '<option value="' . $i . '">' . '0' . $i . '</option>';
  }	
  for($i=10;$i<60;$i+=5) {
    echo '<option value="' . $i . '">' . $i . '</option>';
  }
  ?>
  </select>    
</dd>

<br>
<dt>Will the event be publicized?</dt>
<dd>
  <input type='checkbox' name='eventpub' value=" Public">Yes
  <input type='checkbox' name='eventpub' value=" " checked >No
</dd>
<br>
<dt>Will food be served?</dt>
<dd>
  <input type='checkbox' name='eventfood' value=" Food">Yes
  <input type='checkbox' name='eventfood' value=" " checked>No
</dd>
<br>

<dt>Contact</dt>
<dd>
<input type="text" name="eventcon" size="50">
</dd>

<dt>Description</dt>
<dd>
  <textarea name="eventdesc" cols=50 rows=5></textarea>
</dd>
</fieldset>

<fieldset style="border:none; ">
<blockquote style="background: transparent;"><br>If setup and breakdown time is needed, indicate the amount of time here.  
   If no setup or breakdown time is needed, skip these items.
</blockquote>
<dt>Setup time</dt>
<dd>
  <select name="setuptime">
    <option value=""></option>
    <option value="15">15 minutes</option>
    <option value="30">30 minutes</option>
    <option value="60">60 minutes</option>
    <option value="90">90 minutes</option>
  </select>
</dd>
<dt>Breakdown / cleanup time</dt>
<dd>
  <select name="breakdowntime">
    <option value=""></option>
    <option value="15">15 minutes</option>
    <option value="30">30 minutes</option>
    <option value="60">60 minutes</option>
    <option value="90">90 minutes</option>
  </select>
</dd>
<br>
<br><br><hr><br>
<div class="heading">Location</div>
<blockquote style="background: transparent;">Event location(s) can either be selected from the list
of rooms or the Scheduling Coordinator will assign an appropriate room based on information you
supply as comments before doing your submission.
Please check 
<span onclick="window.open('../webcal/view_v.php?id=13', 'Details', 'height=600,width=700, scrollbars=yes, resizable=yes')" 
style='text-decoration: underline; cursor:pointer;'> room availability</span>
 for your event before booking. 
 If you want to see certain room types check 
the Rooms menu in the calendar page menu at the upper left.
</blockquote>

<?php $rooms = $this->rooms ?>
<?php foreach ($rooms as $room) : ?>
  <div>
    <dt>&nbsp;</dt>
    <input type='checkbox' name='eventloc[]' value=<?php echo "'$room'" ?> > <?php echo $room ?>
  </div>
<?php endforeach ?>
  <div>
    <br>
    <dt>&nbsp;</dt>
    <input type='checkbox' name='eventloc[]' value="NO">No Room Booking Needed
  </div>
<dt>Specify Location if not at CVUUF</dt>
<dd>
<input type="text" name="eventlocoutside" size="50">
</dd>

<br><br><hr><br>


<div class="heading">Does Event Occur More Than One Time?</div>
<br>
<dt>Repeat</dt>
<dd>
  <select name="doesrepeat">
    <option value="daily">daily</option>
    <option value="monthly">other</option>
    <option selected value="no">no</option>
  </select>
</dd>
<br><br>

<div class="heading">If the event repeats:</div>
<dt>End date</dt>
<dd>
<input id='end_dt' name="enddate" value='DD-Mon-YYYY' class='datepicker'><small>Click image for calendar</small>
</dd>
<dt>Main Week in the Month</dt>
<dd>
  <select name="primaryweek">
    <option value=""></option>
    <option value="I1">Every Week</option>
    <option value="I2">Every 2nd Week</option>
    <option value="I4">Every 4th Week</option>
    <option value="1">1st in Month</option>
    <option value="2">2nd in Month</option>
    <option value="3">3rd in Month</option>
    <option value="4">4th in Month</option>
    <option value="-2">Next to last in Month</option>
    <option value="-1">Last in Month</option>
  </select>
</dd>
<dt>Second Week in the Month</dt>
<dd>
  <select name="secondweek">
    <option value=""></option>
    <option value="2">2nd in Month</option>
    <option value="3">3rd in Month</option>
    <option value="4">4th in Month</option>
  </select>
</dd>
<br><br>
<br><br><hr><br>


<blockquote style="background: transparent;">If you want the Scheduling Coordinator to pick a room for you, please note that in the comments
below and include an estimate of the number of people attending your event.  Please include any comments that will help the Scheduling Coordinator complete your 
request quickly.
</blockquote>

<dt>Comments to the Scheduling Coordinator</dt>
<dd>
<textarea name="eventcoms" cols=50 rows=5></textarea>
</dd>

</fieldset>

<br><br><hr><br>
<span style='font-size:120%; font-weight:bold;'>Submit your completed form: </span>    
<INPUT class='submit' TYPE=SUBMIT VALUE="SUBMIT" ID='submitbutton'>
</center>

</form>

<?php $this->pickers = true; ?>
