
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
$('body').on('click', '#rebuildbutton', function(event) {
        var request = $.ajax({
                url: "groupscript",
                type: "POST",
                dataType: "html"
        });
        request.done(function(msg) {
                var start_status = $(msg).find("#script_start_result")
                $("#status").html(start_status);
                function poll(prior, same_limit) {
                        setTimeout(function() {
                                var pollReq = $.ajax({
                                        url: "groupstatus",
                                        type: "GET",
                                        dataType: "html"});
                                pollReq.done(function(data) {
                                        var out = $(data).find("#script_status").text();
                                        if (out != prior) {
                                                poll(out, 15);
                                        } else {
						if (out.indexOf('cleanly finished') != -1) {
							window.location.reload(true);
							return;
						}
                                                if (same_limit <= 0) {
                                                        out += "\n...polling stopped";
                                                } else {
                                                        poll(out, same_limit - 1);
                                                }
                                        }
                                        $("#status").html(out.replace(/(?:\r\n|\r|\n)/g, '<br />'));
                                });
                        }, 2000);
                };
		if (start_status.text().indexOf('NOT') == -1) {
                  poll("", 15);
		}
        });
        request.fail(function(jqXHR, textStatus) {
                $("#status").html("Failed: " + textStatus);
        });
});
</script>
<meta charset="utf-8" />
<input type="submit" id="rebuildbutton" name="groupscript" value="Rebuild" /><br/>
<div id="generated_content">
<? include 'group_contents.html' ?>
</div> <!-- generated_content -->
<br/>
<input type="submit" id="rebuildbutton" name="groupscript" value="Rebuild" /><br/>
<p>
<br/>
<div id="status">
</div>
</p>

