<?php $this->head = "CVUUF Members and Friends" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>

<br><br>
<center>
<strong><big>This directory information is for exclusive use by CVUUF Members and Friends
and is not to be used for any commercial purposes.</big></strong>
</center>
<form method=post>
<br><input type="submit" name="pdfbutton" value="PDF"> Create PDF (printable) directory.
<input type='hidden' name='directory' value="<?php echo $this->directory ?>" >
</form><br>
<p id='index' style='font-size:120%;'>Come back here by clicking the
	<span onClick="parent.location='#index'" onMouseOver="document.body.style.cursor='pointer'"
		onMouseOut="document.body.style.cursor='auto'"><img src="/media/graphics/arrow.plain.up.gif" alt='arrow'></span> symbol.<br>


<?php echo $this->list ?>
<b>Members</b> names are <b>bold.</b>
<br><br>
    <?php if (isset($this->data)) : ?>
<table  border=2px style="empty-cells: show; background-color:white;" >
<tr><th>Name<th>Home Phone<th>Cell Phone<th>Email</tr>
    <?php $data=$this->data ?>
    <?php $initial = '' ?>
<tr>


    <?php foreach($data as $line) : ?>
<?php //var_dump($line[1]); exit; ?>
    <?php if ($line['Last Name'][0] <> $initial) : ?>
        <?php $initial = $line['Last Name'][0] ?>
        <tr>
        <td><span id='initial<?php echo $initial ?>'> <?php echo $initial ?></span>
        <span onClick="parent.location='#index'" onMouseOver="document.body.style.cursor='pointer'"
				onMouseOut="document.body.style.cursor='auto'"><img src="/media/graphics/arrow.plain.up.gif" alt='arrow'></span>
        </tr>
    <?php endif ?>
    <?php $boldon = $boldoff = ''; 
        if ($line['Status'] == 'Member') : 
            $boldon = "<b>"; $boldoff = "</b>";
            endif; ?>
        <tr> 
        <td><?php echo $boldon . $line['First Name']  ." " . $line['Last Name'] . $boldoff ?>
        <td><?php echo $line['Home Phone'] ?>
        <td><?php echo $line['Cell Phone'] ?>
        <td><?php echo $line['Email'] ?>
        </tr>
    <?php endforeach ?>
</table>
    <?php endif ?>

