<?php $this->head = "EMAIL FORWARDING" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
<center>
<strong><big>This directory information is for exclusive use by CVUUF Members and Friends
and is not to be used for any commercial purposes.</big></strong>
</center>

<br><br>

<form method='post'>
<fieldset style="border:none;">
<dt><INPUT TYPE=SUBMIT name='showbutton' VALUE="SHOW"></dt>
<dd>Show forwarders ordered by cvuuf email addresses.</dd>
</fieldset>

<?php if ($this->admin) : ?>
<fieldset style="border:none;">
<dt><INPUT TYPE=SUBMIT name='filebutton' VALUE="FILE"></dt>
<dd>Select new forwarder file to upload.  BE SURE YOU WANT TO DO THIS!!!.</dd>
</fieldset>
<?php endif ?>
</form>