<?php $this->head = "MINUTES MANAGEMENT" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
<form method='post'>

<strong><big>Select minutes type.</big></strong>
<br><br>
<fieldset style="border:none; ">
<dt><input TYPE='submit' name='typebutton' value="TYPE"></dt>
<dd><select name="orgtype">
  <option value='B' <?php if (isset($this->select['B'])) echo 'selected' ?> >Board</option>
  <option value='C' <?php if (isset($this->select['C'])) echo 'selected' ?> >Council</option>
  <option value='F' <?php if (isset($this->select['F'])) echo 'selected' ?> >Fellowship</option>
</select>
</dd>
</fieldset>
<br><hr><br>


<strong><big>If the minutes will have attachments, upload them one at a time here before creating or editing.</big></strong>
<br>
Next upload server file name suggestion is filled in. File type of PDF is strongly suggested. Use the file name as is or change it.<br><br>
<fieldset style="border:none; ">
<dt><input type="submit" name="todo" value="NAME"></dt>
<dd><input type="text" name="newName" size=30 value="<?php echo $this->name ?>"></dd>
<dt>&nbsp;</dt>
<dd>Specify file name</dd>
</fieldset>
<br><hr><br>

<strong><big>Create new minutes</big></strong>
<fieldset style="border:none; ">
<dt><input type="submit" name="createbutton" value="CREATE"></dt>
</dd>Create now</dd>
</fieldset>
<br><hr><br>

<strong><big>Select existing minutes to edit</big></strong>
<br>
<fieldset style="border:none; ">
  <?php $count = 0 ?>
  <?php foreach($this->minutes as $node) : ?>
    <?php $theNode = $node->nodeid ?>
<span style='font-size:8pt;'>[<?php echo $theNode ?>]</span> 
<a href='/support2/minutesmanage?select=<?php echo $theNode ?>'> <?php echo $node->title ?></a><br>
  <?php if ($count++ == 99) break ?>
  <?php endforeach ?>
</fieldset>

<input type="hidden" name="orgcode" size=1 value="<?php echo $this->orgcode ?>"> 

</form>