<center><big><big><b>HOW TO CONTACT US</b></big></big></center>
<br><br>
<br><br>

<big><b>Our street address is </b></big>
<blockquote>
3327 Old Conejo Road
<br>Newbury Park, CA 91320
</blockquote>

<big><b>Our mailing address is </b></big>
<blockquote>
3331 Old Conejo Rd
<br>Newbury Park, CA 91320-2115
</blockquote>

<big><b>Our office phone number is </b></big>
<blockquote>
805-492-8751
</blockquote>

<br><br>
<big><b>If you'd like to email us, please use this form:</b>
<br><br>
<form method="post" action="/contact/formmail.php" name="CVUUF info form">
    <input type="hidden" name="env_report" value="REMOTE_HOST,REMOTE_ADDR,HTTP_USER_AGENT,AUTH_TYPE,REMOTE_USER" />
    <input type="hidden" name="recipients" value="office@cvuuf.org" />
    <input type="hidden" name="required" value="EmailAddr:Your email address,FullName:Your name" />
    <input type="hidden" name="subject" value="CVUUF Information Request" />
    <input type="hidden" name="derive_fields" value="email=EmailAddr,realname=FullName" />
    <input type="hidden" name="mail_options" value="Exclude=email;realname" />

    <table border="0" cellspacing="5%">
    <tr>
        <td align="right">
        Your name:
        </td>
        <td><input type="text" name="FullName" />
        </td>
    </tr>
    <tr>
        <td align="right">
        Your email address:
        </td>
        <td><input type="text" name="EmailAddr" />
        </td>
    </tr>
    <tr>
        <td valign="top" align="right">
        Your message:
        </td>
        <td><textarea name="mesg" rows="10" cols="50"></textarea>
        </td>
    </tr>
    <tr>
        <td> </td>
        <td><input type="submit" value="Submit" /></td>
    </tr>
    <tr>
        <td> </td>
        <td style="text-align:left;"><span style="font-size:50%;">Powered by Tectite <a href="http://www.tectite.com/" target="_blank">contact form</a> processor (FormMail).</span>
        </td>
    </tr>
    </table>
    
    <!-- Mike's additions  -->
    
    <input type="hidden" name="good_url"
       value="/index/formthanks" />

    
    
</form>
