<span class='heading'>Thanks for contacting us!

</span> 
<br><br><br><br>
We've received your information and, if it's appropriate, we'll be in contact with you soon. 
<br><br><br><br>
<div style="text-align:center; font-size:9pt; color:gray;">Your form submission was processed by <a  style='color:gray;' href="http://www.tectite.com/">FormMail</a> (8.36), a PHP script available from <a  style='color:gray;' href="http://www.tectite.com/">www.tectite.com</a>. 
</div>