<DIV style='margin-right:6px; margin-left:6px;'>
  <div style="text-align:center; color:#33715A; font-size:140%; font-weight:bold;">&nbsp;&nbsp;Welcome to the Conejo Valley Unitarian Universalist Fellowship!
  </div>
<br>
  <table>
  <tr>
  <td width=512px valign=top>
    <img src="/media/graphics/front/CVUUF_HomePhotos.jpg" alt="" title="" align="left" >
    <br><br>
    <center>We invite everyone to download our monthly <br><a href='/public/newsletter'><span style='color:blue; font-weight:bold; text-decoration: underline;'> CVUUF Newsletter</span></a></center>
    <center>and our weekly <br><a href='/public/newsandnotes'><span style='color:blue; font-weight:bold; text-decoration: underline; '> News and Notes</span></a></center>
    <br/>
<!-- <center><span style='color:blue; font-weight:bold; font-size:120%;'>Help with the <a href="http://www.togetherauction.com/cvuuf">auction</a>!</span></center> -->
  <td>      
    <p style="font-variant:small-caps; color:#9a160e; font-weight:bold;">Many beliefs. One faith.
    <br><span style="font-weight:bold; margin-bottom:20px; color:black;">Imagine a religion that embraces many different beliefs, including yours.</span> 
    <p >If you're searching for a liberal religious home where people honor each other's beliefs and worship together as one faith, we invite you to join us. We are an open-minded religious community that encourages you to seek your own spiritual path, wherever it leads.</p>
    <p style="font-size:120%; font-weight:bold; text-align:center; color:#9a160e;">Join us for Sunday Services<br >
        9:15 am &amp; 11:00 am</p>
    <p style="text-align:center;"><a href='https://maps.google.com/maps?q=Conejo+Valley+Unitarian+Universalist+Fellowship,+3327+Old+Conejo+Road,+Thousand+Oaks,+CA&amp;hl=en&amp;sll=34.177015,-118.936958&amp;sspn=0.093589,0.155354&amp;oq=conejo&amp;t=h&amp;hq=Conejo+Valley+Unitarian+Universalist+Fellowship,&amp;hnear=3327+Old+Conejo+Rd,+Newbury+Park,+Ventura,+California+91320&amp;z=16&amp;iwloc=A<span style="font-weight:bold; margin-bottom:20px; font-size:100%; color:blue;"'>MAP</a></p>
<br/>
<a href="https://www.youtube.com/watch?v=JXRFNue1-Ck" style="text-decoration: none; font-size: 1.5em;">Steps Toward Compassion</a>
<?php
        $functions = new Cvuuf_functions();
      	$text = $functions->getWebtext();
        echo ($text);
?>
    
  </tr>
  </table>
<br>
</div>

<?php $this->splash = true ?>
  <div style="width:675px; margin-left:auto; margin-right:auto;" >
  <table width='625px' border=0 >
  	<COL span='125'>
  	<COL span='125'>
  	<COL span='125'>
  	<COL span='125'>
  	<COL span='125'>
  	<TR>
    <td align=center width=125px style="background:url(/media/graphics/theme/blankbutton.png); ">
<?php /*<a href="http://tinyurl.com/yd69ntf"><span style="color:white; font-size:80%; font-weight:bold; font-family:Verdana,Tahoma,Arial;"> */ ?>
<a href="https://www.eservicepayments.com/cgi-bin/Vanco_ver3.vps?appver3=tYgT1GfNxRUldiimjHMvOfT3CqSkmBT8sVuLlF25uIzo-7YkZiNiYhc46uwjFenmums9tj3wI7okSf0MyMa8urt3Lz8Rfn-KU8cmMV2hkFA=&ver=3"><span style="color:white; font-size:80%; font-weight:bold; font-family:Verdana,Tahoma,Arial;">
Online Payments</span></a>

    <td width=125px>
    <td align=center width=125px style="background:url(/media/graphics/theme/blankbutton.png)">
<a href="/private"><span style="color:white; font-size:80%; font-weight:bold; font-family:Verdana,Tahoma,Arial;">
  Member Site<br>(log in required)</span></a>
    <td width=125px>
    <td align=center width=125px style="background:url(/media/graphics/theme/blankbutton.png);  ">
<a href="/index/contact"><span style="color:white; font-size:80%; font-weight:bold; font-family:Verdana,Tahoma,Arial;">
Contact</span></a>
    </TR>
  </table>
  </div><br/>
<center><span style="text-align:center; color:gray; font-size: 9pt;"><a href="privacy.html">Privacy Policy</a></span></center>
