<?php $this->head = "Adult Religious Education" ?>
<br><br>

Religious education is available for adults on an on-going basis. Each year we choose a theological theme, 
exploring it together as a congregation through worship, story and in the classroom. Classes are 
taught by professional staff as well as lay leaders. Classes are usually held one night a 
week and can last between 4-13 weeks.

For the 2013-2014 year we will explore the Twelve Steps to a Compassionate Life based on the book of the 
same name by Karen Armstrong. Groups for discussion on the topic will be formed and facilitated by Rev. 
Lora Brandis or Justine Fischer, Director of Religious Education. For more information contact Justine 
at <a href='mailto:dre@cvuuf.org'>dre@cvuuf.org</a>. Dates and times will be listed on our online 
<a href='http://cvuuf.org/calendar'>calendar</a>, 
in the <a href='http://cvuuf.org/public/newsletter'>newsletter</a> or below (if available). 
<p><p>
<b>Living Compassionately with Rev. Lora Brandis and Justine Fischer, DRE - Contact</b> Rev. Lora or Justine. <b>Location:</b> Adult RE.
This year we are studying Karen Armstrong's Twelve Steps to a Compassionate Life as a source for 
reflection in worship and religious education. Rev. Lora and Justine will co-facilitate a 
study group after the second service on the third Sunday of each month. The study group 
is drop-in so there is no need to register. Join us as we move through all twelve steps 
together towards a life constantly guided by compassion.