<?php $this->head = "Adult Religious Education" ?>
<br><br>
Religious education is available for adults on an on-going basis. Each year we choose a theological theme, exploring it together as a congregation through worship, story and in the classroom. Classes are taught by professional staff as well as lay leaders and usually held one night a week and can last between 4-13 weeks.
<p/>
Adult R.E. classes will be offered in the fall of 2015. Until then, you are encouraged to get involved in some of the <a href="http://us9.campaign-archive1.com/home/?u=400639c1114daae501c63a104&id=0ba3014544">many activities</a> at CVUUF.

