<?php $this->head = "RELIGIOUS EDUCATION ATTENDANCE" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>

    <?php $class = $this->class ?>
    <?php $classes = $this->classes ?>
    <?php $theclass = $this->theclass ?>
<?php if ($class <> 'All') : ?>
<form method='post'>
<table  border=2px style="empty-cells: show; background-color:white;" >
<tr><th><th>Class
  <?php foreach ($classes as $aclass) : ?>
<tr>
<td><input type='radio' name='class' value='<?php echo $aclass ?>' ", <?php if(isset($theclass[$aclass])) echo 'checked' ?> > 
<td> <?php echo $aclass ?>
  <?php endforeach ?>
</table>
<br><input class='submit' TYPE=SUBMIT name='action' value='SHOW'> Show selected class
</form>
<br><br>
<hr>
<br><strong><big>Class - <?php echo $class ?></big></strong>
<br><br>
  <?php endif ?>

<form method='post'>
<table  border=2px style="empty-cells: show; background-color:white;" >
<tr><th><th><th>
  <?php $dates = $this->dates ?>
  <?php foreach($dates as $date) : ?>
<td><input type="checkbox" name="did[]" value='<?php echo $date ?>'>
  <?php endforeach ?>
</tr>
<tr><th><th>ID<th>Name
	<?php foreach($dates as $date) : ?>
<th><?php echo substr($date, 5) ?>
<?php endforeach ?>
</tr>

  <?php $data = $this->data ?>
  <?php $attend = $this->attend ?>
  <?php foreach($data as $child) : ?>

<?php //var_dump($child); exit; ?>

    <?php $chid = $child[0] ?>
<tr>
<td><input type="checkbox" name="cid[]" value='<?php echo $chid ?>'>
<td><?php echo $chid ?><td><?php echo $child[1] . ' ' . $child[2] ?>
		  <?php $attChild = isset($attend[$chid]) ? $attend[$chid] : '' ?>
		  <?php foreach($dates as $date) : ?>
<?php //echo "Date $date <br>"; ?>
        <?php if (count($attChild) > 0) 
        {
//echo count($attChild), '<br>';
            $found = FALSE;
            if ($attChild <> '') 
                foreach ($attChild as $chDate)
                {
                    if ($chDate == $date)
                    {
                        $found = TRUE;
                        echo "<td> X";
                        break;
                    }
                }
            if ($found <> TRUE)
              echo "<td> ";
          }  
          else
            echo "<td> "; ?>
       <?php endforeach ?>  
</tr>
    <?php endforeach ?>
</table>

<input type='hidden' name='class' value='<?php echo $class ?>'>
<br><input class='submit' TYPE=SUBMIT name='act' value='MARK'> Mark selected children in attendance on selected date.
<br><input class='submit' TYPE=SUBMIT name='act' value='UNMARK'> Remove selected children from attendance on selected date.
<br><br><input class='submit' TYPE=SUBMIT name='act' value='GUEST'> Create a guest child entry.
</form>