<?php $this->head = "RELIGIOUS EDUCATION ENROLLMENT" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
<strong><big>6. Finish for <?php echo "$this->firstname $this->lastname" ?></big></strong>

<br><br>
<div style='margin-left: 217px;'>


<form method='post'>

What would you like <?php echo $this->firstname ?> to receive from this faith experience?  <br>     
<textarea name="receive" COLS=80 ROWS=6><?php echo stripslashes($this->receive) ?></textarea><br>
<br>
May we contact you to discuss your responses? 
<input type="radio" style="border-style:none;" name="discuss" value="Yes"
	<?php if ($this->discuss == 'Yes') echo 'checked' ?> > Yes
<input type="radio" style="border-style:none;" name="discuss" value="No"
	<?php if ($this->discuss == 'No') echo 'checked' ?> > No 
<br><br>
<hr>
<br>
<strong>Please read the following:</strong><br><br>
<br>
I have read the <a href='re_policies.html' target='policywindow'>CVUUF RE Policies</a> available
<a href='re_policies.html' target='policywindow'>here</a> to read, and I agree to those
policies.<br>
<br><br>
I understand RE groups occasionally visit the park.  I give my permission for
my child to participate in a park activity.  In case of emergency, I authorize the
adult in charge of the RE activity to obtain emergency medical care for my child.<br>
<br><br>
Health Insurance Provider:
<br><textarea name="insurance" COLS=50 ROWS=3><?php echo $this->insurance?></textarea>
<br>Policy/Group #:
<input type="text" name="insnumber" value="<?php echo $this->insnumber?>" size="40"><br>
<br><br>
Parent/Guardian Agreement:<br>
Signature:
<input type="text" name="signame" value="<?php echo $this->signame?>" size="70">
<br>
<br>


<input type='hidden' name='keys' value='<?php echo $this->nextform->getValue('keys') ?>' >
<input type='hidden' name='values' value="<?php echo $this->nextform->getValue('values') ?>" >
<input type="submit" name="changeburronbutton" value="CHANGE">
</form>
<br><br>
</div>
    <?php if (isset($this->nextform)) : ?>
<fieldset style="border:none; font-size:80%;">
    <?php echo $this->nextform; ?>
</fieldset>
    <?php endif ?>