<?php $this->head = "Welcome to CVUUF Religious Education" ?>
<p>Welcome to Conejo Valley Unitarian Universalist Fellowship’s
Lifespan Religious Education Program.  
<img src='/media/photos/Justine Fischer.jpg' width='150' height='200' alt='Justine' border='4' align='left' hspace='12'>
<p>The Religious Education program draws its focus from the
Conejo Valley Unitarian Universalist Fellowship’s mission:
<blockquote><i>Our mission is to nurture spiritually courageous people who transform the world through justice and compassion.</i></blockquote>
As the Director of Religious Education, I am here to help you, your child or youth explore, learn and develop your personal faith within a Unitarian Universalist context.  Although our faith has no specific creed, we do have shared values; our Unitarian Universalist Principles and the Sources of our Unitarian Universalist faith. 
<p>The Religious Education program usually referred to as RE, encourages; spiritual growth, service and living the faith of Unitarian Universalism.
<p>Sunday morning at 9:15 children from birth through middle school meet in groups designed to fit their age and development. High School aged youth meet at 11:15. They are invited to attend the first service or the second, on each Sunday.
<p>Classes are led by spiritual nurturers (teachers) who are volunteer parents and church members.  Parents are expected to lend service to the program at least every other year.
<p>Class curriculums and themes are determined each year and correspond to the theme of the worship service each Sunday.
<p>We welcome you to visit and look forward to seeing you on a Sunday soon.
<p>Yours in faith,
<br>Justine