<?php $this->head = "RELIGIOUS EDUCATION ENROLLMENT" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
<strong><big>7. Review and Submit for <?php echo "$this->firstname $this->lastname" ?></big></strong>
  <?php $data = $this->data ?>
<br><br><br>
<form method='post'>

<strong>1. Child Information:</strong><br>
<span class="label"> Child First Name:</span> <span style='background-color:white;'>
        <?php echo $data['firstname'] ?></span><br>
<span class="label"> Child Last Name:</span> <span style='background-color:white;'>
        <?php echo $data['lastname'] ?></span><br>
<span class="label"> Date of birth:</span> <span style='background-color:white;'>
        <?php echo $data['birth'] ?></span><br>
<span class="label"> Current grade:</span> <span style='background-color:white;'>
        <?php echo $data['grade'] ?></span><br>
<span class="label"> Gender:</span> <span style='background-color:white;'>
        <?php echo $data['gender'] ?></span><br>
<br>
<span class="label"> &nbsp; </span><input type="submit" name="s1button" value="CHANGE 1">
<br><br>
<hr>
<br>

<strong>2. Contact Information:</strong><br>
<br><strong>Primary Contact</strong><br>
    <?php if (isset($data['ppersonid'])) : ?>
<span class="label"> Home Phone:</span> <span style='background-color:white;'>
        <?php echo $data['priphone'] ?></span><br>
<span class="label"> Personal Phone:</span> <span style='background-color:white;'>
        <?php echo $data['pripphone'] ?></span><br>
<span class="label"> Email:</span> <span style='background-color:white;'>
        <?php echo $data['priemail'] ?></span><br>
<br>
    <?php endif ?>
<br><strong>Alternate Contact</strong><br>
    <?php if (isset($data['apersonid'])) : ?>
<span class="label"> Home Phone:</span> <span style='background-color:white;'>
        <?php echo $data['altphone'] ?></span><br>
<span class="label"> Personal Phone:</span> <span style='background-color:white;'>
        <?php echo $data['altpphone'] ?></span><br>
<span class="label"> Email:</span> <span style='background-color:white;'>
        <?php echo $data['altemail'] ?></span><br>
<br>
    <?php endif ?>
<span class="label"> &nbsp; </span><input type="submit" name="s2button" value="CHANGE 2">
<br><br>
<hr>
<br>

<strong>Final submission:</strong>
    <?php if (isset($this->nextform)) : ?>
<fieldset style="border:none; font-size:80%;">
    <?php echo $this->nextform; ?>
</fieldset>
    <?php endif ?>