<?php $this->head = "NEW MEMBER INDUCTION" ?>
    <?php if (isset($this->message)) : ?>
        <?php echo "<hr><b><i>Notice:</i><br> " ?>
        <?php if (gettype($this->message) == 'array') : ?>
            <?php foreach ($this->message as $line) : ?>
                <?php echo $line, '<br>' ?>
            <?php endforeach ?>
        <?php else : ?>
            <?php echo $this->message ?>
        <?php endif ?>
</b><hr><br>
    <?php endif ?>
<br><br>
<center>
<strong><big>This directory information is for exclusive use by CVUUF Members and Friends
and is not to be used for any commercial purposes.</big></strong>
</center>
<br><br>

<br>
<form method=post>
<table  border=2px style="empty-cells: show; background-color:white;" >
<tr><th><th>Name<th>Ask?<th>Member Date<th>Inducted<th>Phone<th>Email</tr>

    <?php foreach ($this->table as $person) : ?>
<tr>

<td><input type="checkbox" name="id[]" value='<?php echo $person['ID'] ?>' >
<td><?php echo $person['Name'] ?>
<td><?php echo $person['Dont'] ?>
<td><?php  echo substr($person['Date'], 5, 2) . "/" . substr($person['Date'], 8, 2)
                 . "/" . substr($person['Date'], 0, 4) ?>
<td><?php echo $person['Inducted'] ?>
<td><?php echo $person['Phone'] ?>
<td><?php echo $person['Email'] ?>
</tr>
    <?php endforeach ?>
</table>

<br><input TYPE=SUBMIT name='ask' value='DON&#8217;T ASK'> Set "don't want induction" for selected people
<br><input TYPE=SUBMIT name='ask' value='OK TO ASK'> Clear "don't want induction" for selected people
<br><br><input TYPE=SUBMIT name='status' value='INDUCTED'> Set 'Inducted' for selected people
<br><input TYPE=SUBMIT name='status' value='NOT INDUCTED'> Clear 'Inducted' for selected people<br>
</form>